### ISSUE TITLE
CPU_MKL Error converting value "CPU_MKL" to type 'Seq2SeqSharp.ProcessorTypeEnums

### ISSUE THREAD

**Issue by piedralaves** [zhongkaifu/Seq2SeqSharp#60]
Hi zhongkai:

If we understand well, to use MKL we need to do:

1. copy files in dll folder to our current working directory  (the place with the console exe?)
2. set ProcessorType to CPU_MKL.

The problem is that we get a "Error converting value "CPU_MKL" to type 'Seq2SeqSharp.ProcessorTypeEnums".

Is is something wrong with our steps?

Thanks a lot

**Comment by piedralaves** [comment]
Could it be caused by a new recent release?

**Comment by zhongkaifu** [comment]
@piedralaves

I cannot repo this error in my side.
Can you please share more details with me? Such as which tool did you run ?, what's command line or config file did you use ? what's the call stack when you got such error, and others.


Thanks
Zhongkai Fu

**Comment by piedralaves** [comment]
Seq2seqConsole.

C:\CUSTOM\seq2seq\seq2seqRobot>cd C:\CUSTOM\seq2seq\Seq2SeqConsole\bin

C:\CUSTOM\seq2seq\Seq2SeqConsole\bin>Seq2SeqConsole.exe -Task Train -ConfigFilePath C:\CUSTOM\seq2seq\seq2seqRobot\config.json
Loading config file from 'C:\CUSTOM\seq2seq\seq2seqRobot\config.json'
info,13/02/2023 21:09:14 Exception: 'Error converting value "CPU_MKL" to type 'Seq2SeqSharp.ProcessorTypeEnums'. Path 'ProcessorType', line 30, position 25.'
info,13/02/2023 21:09:14 Call stack: '   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Seq2SeqConsole.Program.Main(String[] args) in C:\Users\jorge\source\repos\Seq2SeqSharp-RELEASE_2_5_0\Tools\Seq2SeqConsole\Program.cs:line 42'

**Comment by piedralaves** [comment]
The config file is:
[config.json.txt](https://github.com/zhongkaifu/Seq2SeqSharp/files/10725689/config.json.txt)

**Comment by piedralaves** [comment]
Hi again:
We guess the cause is that we dont still have:  this:
[https://github.com/zhongkaifu/Seq2SeqSharp/commit/b9cce76e54b24d2f92a3ffb05adbde177542e185](url)

**Comment by zhongkaifu** [comment]
Yes, that comments was at more than 1 year ago. Maybe you can upgrade it to the recent versions.

Thanks
Zhongkai Fu
